# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self
    submodules: true
  - task: AzureWebApp@1
   inputs:
    azureSubscription: 'Cobani Deployment - EYDEV - Azure Policies'
    appType: 'webApp'
    appName: 'my-web-app'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
   displayName: 'Run a multi-line script'

